dependencies:
  - "smartcontractkit/chainlink-brownie-contracts@0.2.1"

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1"

dotenv: .env

networks:
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: True
  development:
    verify: False
  kovan:
  mainnet:

wallets:
  from_key: ${PRIVATE_KEY}